Check results of matrix jobs in Example Package (All) CI job (#287)
## Motivation

The CI has an `Example Package (All)` job which depends on the matrix
job for checking the example projects. It wasn't actually checking the
result of the matrix job though, so it would be skipped, even if one or
more example matrix jobs failed.

## Modifications

- Check the results of the matrix job in the fan-in CI job

## Result

CI will gate against failed examples.

## Notes

This PR will contain one commit that deliberately poisons the examples,
so we can see the issue (the All job will not be marked as failed). Then
it will be updated with a fix for the All job (which will then fail, as
required). Then we'll revert the commit that poisons the examples.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -128,5 +128,12 @@ jobs:
     name: Example Package (All)
     runs-on: ubuntu-latest
     needs: test-examples
+    if: always()
     steps:
-      - run: echo "All matrix jobs completed"
+      - name: Check all example jobs succeeded
+        run: |
+          if [[ "${{ needs.test-examples.result }}" != "success" ]]; then
+            echo "One or more example matrix jobs failed; failing job."
+            exit 1
+          fi
+          echo "All example matrix jobs succeeded."
